# Generated by Django 4.0.2 on 2022-04-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0002_student_delete_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
